site_name: Chaucha Docs
pages:
    - Home: index.md
    - Community contributions:
      - Novice:
        - Introduction: aportes/principiante/intro.md
        - How to mine chauchas: aportes/principiante/mining.md
        - HODL !: aportes/principiante/hodl.md
        - Security tips: aportes/principiante/sec.md
        - FAQ: aportes/principiante/faq.md
        - Aventuras de Quirquincho (Spanish): aportes/principiante/quirquincho/aventuras.md
      - Advanced:
        - ¿What is a node?: aportes/avanzado/nodo.md
        - Coloring chauchas: aportes/avanzado/pintar.md
    - Chaucha:
      - Whitepaper: chaucha/whitepaper.md
    - Testimony:
      - Chaucha and the drawings: testimonios/leo.md
      - The lost chauchera: testimonios/pablo.md
    - Mapa of projects: map.md

theme:
  name: 'material'
  font:
    text: 'Montserrat'
    code: 'Space Mono'
  palette:
    primary: 'white'
    accent: 'pink'
  logo: 'img/chaucha.svg'

  favicon: 'img/favicon.ico'
  language: 'en'

repo_name: 'proyecto-chaucha/docs'
repo_url: 'https://github.com/proyecto-chaucha/docs'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/proyecto-chaucha'
    - type: 'facebook'
      link: 'https://facebook.com/proyectochaucha'
    - type: 'telegram'
      link: 'https://t.me/chaucha'
  search:
    language: 'en'

extra_css:
  - 'css/extra.css'
